name: Renovate

on:
  workflow_dispatch:

permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: 'Install Tools'
        run: |
          npm update -g npm
          npm ci
      - name: 'Assemble Renovate Environment'
        id: renovate_environment
        run: |
          echo "renovate_environment<<EOF" >> $GITHUB_OUTPUT
          jq -n \
            --arg go_url '*.nikolasgrottendieck.com' \
            --arg go_url '*.nikolasgrottendieck.com' \
            --arg git_key 'url."https://okeanos-azure@dev.azure.com/okeanos-azure/renovate%20me/_git/renovate%20me/_git/".insteadOf' \
            --arg git_value 'https://go.nikolasgrottendieck.com/' \
            '{
            GONOPROXY: $go_url,
            GONOSUMDB: $go_url,
            GOPRIVATE: $go_url,
            GIT_CONFIG_KEY_0: $git_key,
            GIT_CONFIG_VALUE_0: $git_value,
            GIT_CONFIG_COUNT: 1
            }'
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Renovate
        run: npx renovate
        env:
          LOG_LEVEL: debug
          GITHUB_COM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_REPOSITORIES: "Okeanos/renovate-example"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_CUSTOM_ENV_VARIABLES: ${{ steps.renovate_environment.outputs.renovate_environment }}
          RENOVATE_EXPOSE_ALL_ENV: true
